receivers:
  opencensus:

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://host.docker.internal:9009/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: gotocompany
    external_labels:
      service: siren
      team: gotocompany-infra
      environment: development
      host: local
  logging:
    loglevel: debug

extensions:
  health_check:

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: debug
      initial_fields:
        service: my-instance
  pipelines:
    traces:
      receivers: [opencensus]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [opencensus]
      processors: [batch]
      exporters: [prometheusremotewrite, logging]